services:
  payment-db:
    image: postgres:15-alpine
    container_name: payment_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-payment_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Changed to avoid conflict with host's 5432
    networks:
      - payment-network

  backend:
    build: .
    container_name: payment_backend
    restart: always
    depends_on:
      - payment-db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@payment-db:5432/${POSTGRES_DB:-payment_db}
      - ABA_PAYWAY_MERCHANT_ID=${ABA_PAYWAY_MERCHANT_ID}
      - ABA_PAYWAY_API_KEY=${ABA_PAYWAY_API_KEY}
      - ABA_PAYWAY_API_URL=${ABA_PAYWAY_API_URL}
      - ABA_PAYWAY_RETURN_URL=${ABA_PAYWAY_RETURN_URL}
      - ABA_PAYWAY_CONTINUE_SUCCESS_URL=${ABA_PAYWAY_CONTINUE_SUCCESS_URL}
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge

volumes:
  postgres_data:
