"""change to expired at

Revision ID: 3f1b1572248e
Revises: 76a0ca36c7cb
Create Date: 2026-05-31 16:57:13.418003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f1b1572248e"
down_revision: Union[str, None] = "76a0ca36c7cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("expired_at", sa.DateTime(), nullable=True))
    op.drop_column("transaction", "expire_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column(
            "expire_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("transaction", "expired_at")
    # ### end Alembic commands ###
