"""add expired_at

Revision ID: 76a0ca36c7cb
Revises:
Create Date: 2026-05-31 16:51:07.653189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "76a0ca36c7cb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tran_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("md5", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("firstname", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lastname", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("raw_response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("qr_code_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expire_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transaction_md5"), "transaction", ["md5"], unique=False)
    op.create_index(
        op.f("ix_transaction_tran_id"), "transaction", ["tran_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_tran_id"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_md5"), table_name="transaction")
    op.drop_table("transaction")
    # ### end Alembic commands ###
